#!/usr/bin/php
<?php
/*  Author:    $Author: zyounker $
    Revision:  $Revision: 1.18 $
    Filename:  $Source: /cvshome/brutis/brutis,v $
    Date:      $Date: 2010-03-26 21:33:17 $
    Copyright:

    Software License Agreement (BSD License)

    Copyright (c) 2010, Violin Memory, Inc.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are
    met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.

    * Neither the name of Violin Memory, Inc. nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
    OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
    LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
    DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
    THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
    OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/


error_reporting(E_ALL);

function __autoload($class) {
    load_class($class);
}

function load_class($class) {
    include_once(dirname(__FILE__) . '/lib/' . $class . '.php');
}

load_class('Common');
load_class('TaskManager');
load_class('BrutisError');

set_error_handler(array('BrutisError','BrutisErrorHandler'));

set_default_library();


class client extends Task {
    function exec() {
        parent::exec();

        $options = array();

        if ($this->args['verbose']) {
            $options[] = '-v';
        }

        if ($this->args['range_id'] !== NULL) {
            $options[] = '-r ' . $this->args['range_id'];
        }

        if ($this->args['job_id'] !== NULL) {
            $options[] = '-j ' . $this->args['job_id'];
        }

        if (isset($this->args['collector']['host'])) {
            $options[] = '-C ' . $this->args['collector']['host'] 
                . ':' . $this->args['collector']['port'];
        }
        $options[] = '-t ' . $this->args['test'];
        $options[] = '-x ' . $this->args['serverlist'];

        pcntl_exec(dirname(__FILE__) . '/client', $options);
    }

    function finish() {
        parent::finish();
        if ($this->exit_code > 0) {
            echo("Client exit code: " . $this->exit_code . "\n");
        }
    }
}

class collector extends Task {
    function exec() {
        parent::exec();

        $options = array();

        if ($this->args['verbose']) {
            $options[] = '-v';
        }

        if ($this->args['filename'] != NULL) {
            $options[] = '-o ' . $this->args['filename'];
        }

        if ($this->args['format'] != NULL) {
            $options[] = '-F ' . $this->args['format'];
        }

        if ($this->args['brutisweb'] != NULL) {
            $options[] = '-w ' . $this->args['brutisweb'];
        }

        $options[] = '-C ' . $this->args['collector']['host'] 
            . ':' . $this->args['collector']['port'];


        pcntl_exec(dirname(__FILE__) . '/collector', $options);
    }

    function funish() {
        parent::finish();
        if ($this->exit_code > 0) {
            echo("Collector exit code: " . $this->exit_code . "\n");
        }
    }
}

function init_brutis_settings($argc, $argv) {
    global $settings;
    global $path;

    $options = getopt('c:x:vho:F:w:Xt:');
    if (isset($options['h'])
        || !isset($options['t'])
        || !isset($options['x'])) {
        echo("\nUsage: brutis -t <test_name> -x <serverlist,> [OPTIONS]\n"
            . "    -h                        Help\n"
            . "    -v                        Verbose\n"
            . "    -t <test_config>          Test to run\n"
            . "    -X                        Don't start collector\n"
            . "    -c <collector>            Collector host:port\n"
            . "    -x <serverlist,>          List of Memcache Servers\n"
            . "    -o <output_filename>      Output file\n"
            . "    -F <format>               Output format (csv, json)\n"
            . "    -w <url>                  BrutisWeb\n"
            . "\n\n");
        exit(1);
    }

    $settings['verbose'] = FALSE;
    if (isset($options['v'])) {
        $settings['verbose'] = TRUE;
    }

    $settings['filename'] = NULL;
    if (isset($options['o'])) {
        $settings['filename'] = $options['o'];
    }

    $settings['format'] = NULL;
    if (isset($options['F'])) {
        $settings['format'] = $options['F'];
    }

    $settings['brutisweb'] = NULL;
    if (isset($options['w'])) {
        $settings['brutisweb'] = (string) trim($options['w']);
    }

    $settings['disable_collector'] = FALSE;
    if (isset($options['X'])) {
        $settings['disable_collector'] = TRUE;
    }

    if (isset($options['c'])) {
        parse_collector($options['c']);
    }

    parse_server_list($options['x']);
    parse_test($options['t']);

}

function get_port($host, $port, $limit) {
    $done = FALSE;
    $i = 0;
    while ($done == FALSE && $i <= $limit) {
        $sock = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
        socket_set_option($sock, SOL_SOCKET, SO_REUSEADDR, 1);
        if (@socket_bind($sock, $host, $port)) {
            $done = TRUE;
            break;
        }
        socket_close($sock);
        $port++;
        $i++;
    }

    if ($done == FALSE) {
        return NULL;
    } else {
        return $port;
    }
}



# MAIN

$tm = new TaskManager();
$settings = array();
init_brutis_settings($argc, $argv);

if (!isset($settings['collector'])) { 
    $settings['collector']['host'] = host_to_addr('localhost');
    $settings['collector']['port'] = get_port(
        $settings['collector']['host'], 9091, 128);
}

$job_id = 1;
foreach ($settings['config']->getJobs() as $job) {
    if ($settings['filename'] !== NULL 
        || $settings['verbose'] == TRUE 
        || $settings['brutisweb'] !== NULL) {

        if ($settings['collector']['port'] === NULL) {
            echo("Unable to start collector, no ports available.\n");
            echo("Exiting...\n");
            exit(1);
        } 
    }

    if (!$settings['disable_collector']) {
        $tm->add_task(new collector(), $settings);
    }

    $settings['forks'] = $job->getForks();
    $settings['range_id'] = NULL;
    $settings['job_id'] = $job_id;
    for ($i = 1; $i <= $settings['forks']; $i++) {
        $settings['range_id'] = $i;
        $tm->add_task(new client(), $settings);
    }
    $tm->run();
    $tm->reset();
    $job_id++;
}

?>
